[mypy]
python_version = 3.12
strict = True
warn_unused_ignores = True
warn_redundant_casts = True
disallow_any_unimported = True
show_error_codes = True

[mypy-pystray.*]
ignore_missing_imports = True

[mypy-inspectorctl.tray.__main__]
disallow_any_unimported = False

[mypy-PIL.*]
ignore_missing_imports = True

[mypy-inotify_simple.*]
ignore_missing_imports = True

[mypy-inspectord.workers.fim_watcher.__main__]
disallow_any_unimported = False

[mypy-inspectord._native]
ignore_missing_imports = True

[mypy-inspectord.workers.process_collector.__main__]
disallow_any_unimported = False
