"""Tests for the firewall_inspector ruleset diff source.

All tests inject ``runner`` or ``capture`` callables so they never invoke
real subprocesses or require root privileges.
"""

from __future__ import annotations

import subprocess
from collections.abc import Callable
from typing import Any

import pytest

from inspectord.workers.firewall_inspector.source import (
    FirewallSource,
    _capture_ruleset,
    _diff_summary,
    _digest,
)

# ---------------------------------------------------------------------------
# _digest
# ---------------------------------------------------------------------------

_TEXT_A = "table inet filter {\n  chain input { drop }\n}\n"
_TEXT_B = "table inet filter {\n  chain input { accept }\n}\n"


def test_digest_same_text_same_result() -> None:
    assert _digest(_TEXT_A) == _digest(_TEXT_A)


def test_digest_different_text_different_result() -> None:
    assert _digest(_TEXT_A) != _digest(_TEXT_B)


def test_digest_empty_string_is_stable() -> None:
    assert _digest("") == _digest("")


# ---------------------------------------------------------------------------
# _diff_summary
# ---------------------------------------------------------------------------

_OLD_RULES = "table inet filter {\n  chain input { drop }\n}\n"
_NEW_RULES = "table inet filter {\n  chain input { accept }\n  chain forward { drop }\n}\n"


def test_diff_summary_counts_added_and_removed() -> None:
    result = _diff_summary(_OLD_RULES, _NEW_RULES)
    # "drop" line is removed, "accept" and "chain forward { drop }" are added
    assert result["removed"] >= 1
    assert result["added"] >= 1
    assert isinstance(result["diff"], str)
    assert len(result["diff"]) > 0


def test_diff_summary_identical_texts() -> None:
    result = _diff_summary(_OLD_RULES, _OLD_RULES)
    assert result["added"] == 0
    assert result["removed"] == 0
    assert result["diff"] == ""


def test_diff_summary_truncates_at_max_lines() -> None:
    # Build old/new texts that produce a diff longer than max_lines=5.
    old_lines = [f"rule {i} drop" for i in range(20)]
    new_lines = [f"rule {i} accept" for i in range(20)]
    old = "\n".join(old_lines)
    new = "\n".join(new_lines)
    result = _diff_summary(old, new, max_lines=5)
    assert result["diff"].endswith("… (truncated)")
    # The diff text should have exactly 6 lines (5 content + truncation marker).
    assert len(result["diff"].splitlines()) == 6


def test_diff_summary_no_truncation_when_within_limit() -> None:
    result = _diff_summary(_OLD_RULES, _NEW_RULES, max_lines=200)
    assert "… (truncated)" not in result["diff"]


# ---------------------------------------------------------------------------
# _capture_ruleset
# ---------------------------------------------------------------------------


def _make_runner(
    outcomes: dict[str, Any],
) -> Callable[..., subprocess.CompletedProcess[str]]:
    """Return a fake runner that dispatches on the first element of *cmd*.

    *outcomes* maps command name (str) to either:
    - a ``subprocess.CompletedProcess`` instance / object with ``.returncode``
      and ``.stdout``, or
    - an exception class/instance to raise.
    """

    def runner(
        cmd: list[str],
        **_kwargs: Any,
    ) -> subprocess.CompletedProcess[str]:
        key = cmd[0]
        outcome = outcomes[key]
        if isinstance(outcome, BaseException) or (
            isinstance(outcome, type) and issubclass(outcome, BaseException)
        ):
            raise outcome
        return outcome  # type: ignore[return-value]

    return runner


def _ok(stdout: str) -> subprocess.CompletedProcess[str]:
    return subprocess.CompletedProcess(args=[], returncode=0, stdout=stdout)


def _fail(stdout: str = "") -> subprocess.CompletedProcess[str]:
    return subprocess.CompletedProcess(args=[], returncode=1, stdout=stdout)


def test_capture_ruleset_nft_success() -> None:
    runner = _make_runner({"nft": _ok("table inet filter {}")})
    backend, text = _capture_ruleset(runner=runner)
    assert backend == "nftables"
    assert text == "table inet filter {}"


def test_capture_ruleset_nft_missing_falls_through_to_iptables() -> None:
    runner = _make_runner(
        {
            "nft": FileNotFoundError("nft not found"),
            "iptables-save": _ok("# Generated by iptables-save\n"),
        }
    )
    backend, _text = _capture_ruleset(runner=runner)
    assert backend == "iptables"


def test_capture_ruleset_both_unavailable_returns_none() -> None:
    runner = _make_runner(
        {
            "nft": FileNotFoundError("nft not found"),
            "iptables-save": FileNotFoundError("iptables-save not found"),
        }
    )
    backend, text = _capture_ruleset(runner=runner)
    assert backend == "none"
    assert text == ""


def test_capture_ruleset_nft_nonzero_falls_through() -> None:
    runner = _make_runner(
        {
            "nft": _fail("error: ..."),
            "iptables-save": _ok("# iptables rules\n"),
        }
    )
    backend, _text = _capture_ruleset(runner=runner)
    assert backend == "iptables"


def test_capture_ruleset_timeout_falls_through() -> None:
    runner = _make_runner(
        {
            "nft": subprocess.TimeoutExpired(cmd=["nft"], timeout=10),
            "iptables-save": _ok("# iptables rules\n"),
        }
    )
    backend, _text = _capture_ruleset(runner=runner)
    assert backend == "iptables"


# ---------------------------------------------------------------------------
# FirewallSource
# ---------------------------------------------------------------------------


def _make_capture(*snapshots: tuple[str, str]) -> Callable[[], tuple[str, str]]:
    """Return a callable that yields each ``(backend, text)`` tuple in turn."""
    seq = list(snapshots)
    idx = 0

    def capture() -> tuple[str, str]:
        nonlocal idx
        val = seq[idx]
        idx = min(idx + 1, len(seq) - 1)
        return val

    return capture


_NFT_A = ("nftables", "table inet filter {\n  chain input { drop }\n}\n")
_NFT_B = ("nftables", "table inet filter {\n  chain input { accept }\n}\n")
_NONE = ("none", "")
_IPT_A = ("iptables", "# Generated\n-A INPUT -j DROP\n")


def test_source_baseline_not_emitted_on_first_poll() -> None:
    """Ruleset present at construction must NOT appear on the first poll."""
    capture = _make_capture(_NFT_A, _NFT_A)
    src = FirewallSource(capture=capture)
    result = src.poll(timeout_ms=0)
    assert result == []


def test_source_rule_change_emits_record() -> None:
    """A ruleset change after baseline emits one firewall_ruleset_changed record."""
    capture = _make_capture(_NFT_A, _NFT_B)
    src = FirewallSource(capture=capture)
    result = src.poll(timeout_ms=0)
    assert len(result) == 1
    rec = result[0]
    assert rec["action"] == "firewall_ruleset_changed"
    assert rec["backend"] == "nftables"
    assert rec["previous_digest"] == _digest(_NFT_A[1])
    assert rec["digest"] == _digest(_NFT_B[1])
    assert rec["added"] >= 1
    assert rec["removed"] >= 1
    assert isinstance(rec["diff"], str)


def test_source_identical_ruleset_emits_nothing() -> None:
    """No records emitted when the ruleset is unchanged across polls."""
    capture = _make_capture(_NFT_A, _NFT_A, _NFT_A)
    src = FirewallSource(capture=capture)
    assert src.poll(timeout_ms=0) == []
    assert src.poll(timeout_ms=0) == []


def test_source_none_to_readable_emits_nothing() -> None:
    """Transition from no-firewall to readable backend is silently adopted."""
    capture = _make_capture(_NONE, _NFT_A)
    src = FirewallSource(capture=capture)
    result = src.poll(timeout_ms=0)
    assert result == []


def test_source_readable_to_none_emits_nothing() -> None:
    """Transition from readable backend to none is silently adopted."""
    capture = _make_capture(_NFT_A, _NONE)
    src = FirewallSource(capture=capture)
    result = src.poll(timeout_ms=0)
    assert result == []


def test_source_close_is_idempotent() -> None:
    capture = _make_capture(_NFT_A)
    src = FirewallSource(capture=capture)
    assert src._closed is False
    src.close()
    assert src._closed is True
    src.close()  # must not raise
    assert src._closed is True


def test_source_poll_raises_after_close() -> None:
    """poll() must raise RuntimeError after close() has been called."""
    capture = _make_capture(_NFT_A, _NFT_A)
    src = FirewallSource(capture=capture)
    src.close()
    with pytest.raises(RuntimeError, match="closed"):
        src.poll(timeout_ms=0)


def test_source_snapshot_advances_after_change() -> None:
    """After emitting a change, the new snapshot becomes the baseline."""
    capture = _make_capture(_NFT_A, _NFT_B, _NFT_B)
    src = FirewallSource(capture=capture)
    # First poll: change detected
    result1 = src.poll(timeout_ms=0)
    assert len(result1) == 1
    # Second poll: same ruleset as first poll result — no change
    result2 = src.poll(timeout_ms=0)
    assert result2 == []


def test_source_iptables_backend_change_emits_record() -> None:
    """Works with iptables backend too."""
    ipt_b = ("iptables", "# Generated\n-A INPUT -j ACCEPT\n")
    capture = _make_capture(_IPT_A, ipt_b)
    src = FirewallSource(capture=capture)
    result = src.poll(timeout_ms=0)
    assert len(result) == 1
    assert result[0]["backend"] == "iptables"
